---

- name: Configure Ghost
  import_tasks: ghost.yml
  tags:
    - ghost
  
- name: Configure Nginx proxy
  import_tasks: nginx.yml
  tags:
    - ghost
    - web

- name: Update Ghost
  import_tasks: update.yml
  tags:
    - ghost
    - update
...