all:
  vars:
    env_name: "prod"
  children:
    blog:
      hosts:
        jenniferplusplus.com:
    mysql:
      hosts:
        jenniferplusplus.com:
    web:
      vars:
        use_ssl: yes
        site_url: "https://jenniferplusplus.com"
        nginx_server_name: "jenniferplusplus.com"
      hosts:
        jenniferplusplus.com: