---

- name: Bootstrap and update hosts
  hosts: all
  vars_files:
    - "vars/all.yml"
  tags: bootstrap
  roles: 
    - bootstrap
    - common

- name: System updates
  hosts: all
  vars_files:
    - "vars/all.yml"
  tags: update
  roles:
    - common

- name: Configure monitoring
  hosts: all
  vars_files:
    - vars/all.yml
    - vars/secrets.yml
  tags:
    - monitor
  roles:
    - monitor

- name: Configure Web servers
  hosts: web
  vars_files:
    - "vars/all.yml"
  tags: web
  roles: 
    - web

- name: Configure MySql servers
  hosts: mysql
  vars_files:
    - "vars/all.yml"
    - vars/secrets.yml
  tags: mysql
  roles: 
    - mysql

- name: Configure blog servers
  hosts: blog
  vars_files:
    - "vars/all.yml"
    - vars/secrets.yml
  tags: blog
  roles: 
    - node
    - blog
