- name: add influxdata PPA signing key
  become: true
  ansible.builtin.get_url:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    dest: /etc/apt/influxdata-archive_compat.gpg.key
    checksum: sha256:393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c

- name: add influxdata PPA
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/influxdata-archive_compat.gpg.key] https://repos.influxdata.com/debian stable main
    state: present

- name: install telegraf
  become: true
  ansible.builtin.apt:
    update_cache: no
    name:
      - telegraf
    state: latest
  notify: restart telegraf

- name: copy telegraf influxdb config
  become: true
  ansible.builtin.template:
    dest: /etc/telegraf/telegraf.d/influxdb.telegraf.conf
    src: templates/influxdb.telegraf.conf.j2
    owner: telegraf
    mode: 0640
  notify: restart telegraf
