apiVersion: 1

datasources:
  - name: TestData
    type: testdata

  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    isDefault: true
    access: proxy
    url: http://localhost:8086
    jsonData:
      dbName: default
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token {{ secret.influxdb.accessToken | default(influxdb_access_token, true) }}'
      
  - name: MySQL
    type: mysql
    url: localhost:3306
    user: grafana
    jsonData:
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: '{{ secret.mysql.grafana_ds }}'