{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "innodb_data_read" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "bytes_read" ], "type": "alias" }
      ],
      [
       { "params": [ "innodb_data_written" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "bytes_written" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "jenniferplusplus" }
     ]
    }
   ]
  },
  {
   "title": "Net",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "query": "SELECT non_negative_difference(sum(\"read\")) AS \"read\", non_negative_difference(sum(\"write\")) AS \"write\", non_negative_difference(sum(=~\"/index_io_waits_seconds/\")) AS \"write\" FROM \"autogen\".\"mysql_perf_schema\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "bytes_sent" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "bytes_rcvd" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "threads_connected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "connections" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "connection_errors_max_connections"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "connections rejected (over limit)"
        ],
        "type": "alias"
       }
      ],
      [
       { "params": [ "max_used_connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "peak connections" ], "type": "alias" }
      ],
      [
       { "params": [ "aborted_clients" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "aborted connections" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connected Users",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT IFNULL(usr,'All Connections') ,COUNT(1) Connections\r\nFROM\r\n(\r\n    SELECT user usr,LEFT(host,LOCATE(':',host) - 1) hst\r\n    FROM information_schema.processlist\r\n    WHERE user NOT IN ('system user','root')\r\n) A GROUP BY usr WITH ROLLUP\r\nORDER BY usr;"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}