{
 "title": "Nginx",
 "description": "Performance metrics for Nginx",
 "tags": [
  "Nginx",
  "InfluxDB",
  "Telegraf"
 ],
 "time": { "from": "now-6h", "to": "now-10s" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES FROM \"nginx\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "System $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "host",
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "short",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "medium",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "long",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "recveived",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Nginx $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "host",
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP jenniferplusplus.com",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_resp_code",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "resp_code::tag" ], "type": "tag" }
     ],
     "measurement": "nginxlog",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "resp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "httphost::tag", "operator": "=", "value": "jenniferplusplus.com" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_resp_code",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "resp_code::tag" ], "type": "tag" }
     ],
     "measurement": "nginxlog",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "request" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Verbs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_verb",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "verb" ], "type": "tag" }
     ],
     "measurement": "nginxlog",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "request" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "HTTP 1xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "nginxlog",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "resp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^1/" }
     ]
    },
    {
     "alias": "HTTP  2xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "nginxlog",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "resp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^2/" }
     ]
    },
    {
     "alias": "HTTP  3xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "nginxlog",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "resp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^3/" }
     ]
    },
    {
     "alias": "HTTP  4xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "nginxlog",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "resp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^4/" }
     ]
    },
    {
     "alias": "HTTP  5xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "nginxlog",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "resp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^5/" }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "measurement": "nginxlog",
     "select": [
      [
       { "params": [ "time" ], "type": "field" }
      ],
      [
       { "params": [ "client_ip" ], "type": "field" }
      ],
      [
       { "params": [ "verb" ], "type": "field" }
      ],
      [
       { "params": [ "httphost" ], "type": "field" }
      ],
      [
       { "params": [ "request" ], "type": "field" }
      ],
      [
       { "params": [ "resp_code" ], "type": "field" }
      ],
      [
       { "params": [ "resp_bytes" ], "type": "field" }
      ],
      [
       { "params": [ "referrer" ], "type": "field" }
      ],
      [
       { "params": [ "agent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "httphost::tag", "operator": "!=", "value": "grafana.jenniferplusplus.com" },
      { "condition": "AND", "key": "httphost", "operator": ">", "value": "''" },
      { "condition": "AND", "key": "client_ip::field", "operator": "!=", "value": "15.204.9.146" }
     ]
    }
   ]
  },
  {
   "title": "Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx",
     "select": [
      [
       { "params": [ "accepts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "accepts" ], "type": "alias" }
      ],
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "handled" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "handled" ], "type": "alias" }
      ],
      [
       { "params": [ "reading" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "reading" ], "type": "alias" }
      ],
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "requests" ], "type": "alias" }
      ],
      [
       { "params": [ "waiting" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "waiting" ], "type": "alias" }
      ],
      [
       { "params": [ "writing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "writing" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "repeat": "host",
   "targets": [
    {}
   ]
  },
  {
   "title": "TCP",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "activeopens",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "tcp_activeopens" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "estabresets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "tcp_estabresets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Traf",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}