all:
  vars:
    env_name: "local"
  children:
    blog:
      hosts:
        "jenniferplusplus.vagrant":
    mysql:
      hosts:
        "jenniferplusplus.vagrant":
    web:
      vars:
        use_ssl: no
        site_url: "http://jenniferplusplus.local"
        nginx_server_name: "jenniferplusplus.local"
      hosts:
        "jenniferplusplus.vagrant":