- setup:
- name: backup ghost assets
  ansible.builtin.archive:
    path: /var/www/{{site_name}}/content
    dest: /home/ansible/{{site_name}}.content.{{ansible_date_time.iso8601}}.zip
    format: zip

- name: export backup
  ansible.builtin.fetch:
    dest: './backup'
    src: '/home/ansible/{{site_name}}.content.{{ansible_date_time.iso8601}}.zip'

- name: cleanup
  ansible.builtin.file:
    path: '/home/ansible/{{site_name}}.content.{{ansible_date_time.iso8601}}.zip'
    state: absent