- name: install ghost-cli
  become: true
  community.general.npm:
    name: ghost-cli
    global: true
    production: true
    version: latest

- name: "create ghost user group"
  become: true
  ansible.builtin.group:
    name: ghost
    state: present
  register: ghost_group

- name: "create ghost user"
  become: true
  ansible.builtin.user:
    name: ghost
    group: ghost
    state: present
    create_home: no
    shell: /sbin/nologin
    password_lock: yes
  register: ghost_user

- name: "create site root dir"
  become: true
  ansible.builtin.file:
    path: /var/www/{{site_name}}
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: install ghost
  ansible.builtin.command:
    chdir: /var/www/{{site_name}}
    creates: .ghost-cli
    argv:
      - ghost
      - install
      - "--no-setup"
  notify: restart ghost

- name: change ownership of content dir
  become: true
  ansible.builtin.file:
    path: /var/www/{{site_name}}/content
    state: directory
    owner: ghost
    group: ghost
    recurse: yes
  notify: restart ghost

- name: copy site config
  become: true
  ansible.builtin.template:
    src: files/config.production.json.j2
    dest: /var/www/{{site_name}}/config.production.json
    mode: 0660
    owner: ghost
    group: root
  notify: restart ghost

- name: copy global config
  ansible.builtin.template:
    src: files/ghost.config.j2
    dest: /home/ansible/.ghost/config
    mode: 0644

- name: copy ghost service definition
  become: true
  ansible.builtin.template:
    src: files/ghost.service.j2
    dest: /lib/systemd/system/ghost.service
    mode: 0644
  notify: restart ghost

- name: copy local config
  ansible.builtin.template:
    src: files/ghost-cli.j2
    dest: /var/www/{{site_name}}/.ghost-cli
    mode: 0644

- name: enable site
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{nginx_server_name}}.conf
    dest: /etc/nginx/sites-enabled/{{nginx_server_name}}.conf
    state: link
  notify: restart ghost

- name: start ghost
  become: true
  ansible.builtin.service:
    name: ghost_{{site_name}}
    state: started
    enabled: yes
    

####
# included task files

- name: take backup
  include: backup.yml
  tags:
    - backup
    - backup_content
    - never

- name: restore from backup
  include: restore.yml
  tags:
    - restore
    - restore_content
    - never

- name: update ghost
  include: update.yml
  tags:
    - update
    - update_blog