- name: db backup
  community.mysql.mysql_db:
    state: dump
    name: '{{site_name}}_prod'
    target: '/home/ansible/{{site_name}}_prod.sql'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    pipefail: true

- name: export backup
  ansible.builtin.fetch:
    dest: './backup'
    # src: "/home/ansible/{{site_name}}_prod.{{ansible_facts.ansible_date_time.date}}.sql"
    src: '/home/ansible/{{site_name}}_prod.sql'

- name: cleanup
  ansible.builtin.file:
    path: '/home/ansible/{{site_name}}_prod.sql'
    state: absent