- name: start Mysql
  become: true
  ansible.builtin.service:
    name: mysql
    state: started

- name: root user password
  become: true
  community.mysql.mysql_user:
    name: root
    password: "{{mysql_root_pw}}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_password: "{{mysql_root_pw}}"
    check_implicit_admin: yes
  notify: restart mysql

- name: ansible user cnf
  ansible.builtin.template:
    src: files/my.cnf.j2
    dest: /home/ansible/.my.cnf
    mode: 0660
    owner: ansible
  notify: restart mysql

- name: add mysql user for ghost
  community.mysql.mysql_user:
    name: ghost
    password: "{{mysql_ghost_pw}}"
    priv: 'jenniferplusplus_prod.*:ALL'
  notify: restart mysql