- name: install mysql utilities
  become: true
  apt:
    name:
      - mysql-server
      - certbot
      - python3-certbot-nginx
    state: latest

- name: start Mysql
  become: true
  ansible.builtin.service:
    name: mysql
    state: started

- name: set root user password
  become: true
  community.mysql.mysql_user:
    name: root
    password: "{{mysql_root_pw}}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes
  notify: restart mysql

# Ansible will connect to mysql and perform actions with these credentials in future steps
- name: set default credentials for ansible
  ansible.builtin.template:
    src: files/my.cnf.j2
    dest: /home/ansible/.my.cnf
    mode: 0660
    owner: ansible

# Also allow root to connect to mysql with the same credentials, to enable rotating secrets
- name: set default credentials for root
  become: true
  ansible.builtin.template:
    src: files/my.cnf.j2
    dest: /root/.my.cnf
    mode: 0600
    owner: root

- name: add mysql user for ghost
  community.mysql.mysql_user:
    name: ghost
    password: "{{mysql_ghost_pw}}"
    priv: "{{site_name}}_prod.*:ALL"
  notify: restart mysql

- name: take backup
  include: backup.yml
  tags:
    - backup
    - backup_db
    - never

- name: restore from backup
  include: restore.yml
  tags:
    - restore
    - restore_db
    - never
  notify: restart mysql