- name: restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: restart telegraf
  tags: always
  become: true
  ansible.builtin.service:
    name: telegraf
    state: restarted