- name: copy backup file
  ansible.builtin.unarchive:
    src: backup/{{ansible_host}}/home/ansible/{{site_name}}.sql.zip
    dest: "/home/ansible"

- name: drop existing db
  community.mysql.mysql_db:
    name: "{{site_name}}_prod"
    state: absent

- name: db restore from backup
  community.mysql.mysql_db:
    name: "{{site_name}}_prod"
    state: import
    target: "/home/ansible/{{site_name}}.sql"
    pipefail: yes

- name: cleanup
  when: false
  ansible.builtin.file:
    path: "/home/ansible/{{site_name}}.sql"
    state: absent