- name: add nodejs PPA signing key
  become: true
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    dest: /etc/apt/nodesource.gpg.key

- name: add nodejs PPA
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/nodesource.gpg.key] https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
    state: present

- name: add nodejs source PPA
  become: true
  ansible.builtin.apt_repository:
    repo: "deb-src [arch=amd64 signed-by=/etc/apt/nodesource.gpg.key] https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
    state: present

- name: install services
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name:
      - nodejs
    state: latest