- name: add grafana PPA signing key
  become: true
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/grafana.gpg.key

- name: (temp) remove grafana PPA
  when: false
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/grafana.gpg.key] https://apt.grafana.com stable main
    state: absent    

- name: add grafana PPA
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/grafana.gpg.key] https://apt.grafana.com stable main
    state: present

- name: install services
  become: true
  ansible.builtin.apt:
    update_cache: no
    name:
      - grafana
    state: latest
  notify: restart telegraf

- name: configure grafana
  become: true
  ansible.builtin.template:
    src: templates/grafana.ini
    dest: /etc/grafana/grafana.ini
    mode: 0640
    owner: root
  notify: restart grafana


- name: enable grafana service
  become: true
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes