- name: system upgrade
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: "yes"

- name: install common utilities
  become: true
  apt:
    name:
      - zip
      - unzip
    state: latest

- name: reboot
  tags:
    - reboot
  debug:
    msg: "this is where I would do a reboot task, if I had one"