- name: restart telegraf
  become: true
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: restart influxdb
  become: true
  ansible.builtin.service:
    name: influxdb
    state: restarted

- name: restart grafana
  become: true
  ansible.builtin.service:
    name: grafana-server
    state: restarted