- name: restart ghost
  become: true
  ansible.builtin.service:
    name: ghost_{{site_name}}
    state: restarted

- name: restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: restart telegraf
  become: true
  ansible.builtin.service:
    name: telegraf
    state: restarted