- name: restart mysql
  become: true
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: restart telegraf
  tags: always
  become: true
  ansible.builtin.service:
    name: telegraf
    state: restarted