---

- name: Configure MySQL
  hosts: mysql
  vars_files:
    - '{{ site_secrets }}'
  vars:
    mysql:
      users:
        - 'ghost'
        - 'grafana'
      backup:
        - 'ghost'
  roles:
    - common
    - influxdb
    - mysql
